local lexers = vis.lexers

local base = '#191724'
local surface = '#1f1d2e'
local overlay = '#26233a'
local muted = '#6e6a86'
local subtle = '#908caa'
local text = '#e0def4'
local love = '#eb6f92'
local gold = '#f6c177'
local rose = '#ebbcba'
local pine = '#31748f'
local foam = '#9ccfd8'
local iris = '#c4a7e7'
local highlight_low = '#21202e'
local highlight_med = '#403d52'
local highlight_high = '#524f67'

lexers.STYLE_DEFAULT = 'back:'..base..',fore:'..text
lexers.STYLE_NOTHING = 'back:'..base
lexers.STYLE_CLASS = 'fore:'..foam..',bold'
lexers.STYLE_COMMENT = 'fore:'..subtle
lexers.STYLE_CONSTANT = 'fore:'..gold
lexers.STYLE_DEFINITION = 'fore:'..text
lexers.STYLE_ERROR = 'fore:'..love..',bold'
lexers.STYLE_FUNCTION = 'fore:'..rose
lexers.STYLE_KEYWORD = 'fore:'..pine
lexers.STYLE_LABEL = 'fore:'..text
lexers.STYLE_NUMBER = 'fore:'..gold
lexers.STYLE_OPERATOR = 'fore:'..subtle
lexers.STYLE_REGEX = 'fore:'..gold
lexers.STYLE_STRING = 'fore:'..gold
lexers.STYLE_PREPROCESSOR = 'fore:'..iris
lexers.STYLE_TAG = 'fore:'..foam
lexers.STYLE_TYPE = 'fore:'..foam
lexers.STYLE_VARIABLE = 'fore:'..text
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = 'fore:'..text
lexers.STYLE_IDENTIFIER = 'fore:'..rose
lexers.STYLE_LINENUMBER = 'fore:'..muted
lexers.STYLE_LINENUMBER_CURSOR = 'fore:'..rose
lexers.STYLE_CURSOR = 'fore:'..base..',back:'..text
lexers.STYLE_CURSOR_PRIMARY = lexers.STYLE_CURSOR
lexers.STYLE_CURSOR_LINE = 'back:'..highlight_low
lexers.STYLE_COLOR_COLUMN = 'back:'..surface
lexers.STYLE_SELECTION = 'back:'..highlight_med
lexers.STYLE_STATUS = 'back:'..surface..',fore:'..text
lexers.STYLE_STATUS_FOCUSED = 'back:'..overlay..',fore:'..rose..',bold'
lexers.STYLE_SEPARATOR = lexers.STYLE_DEFAULT
lexers.STYLE_INFO = 'fore:'..foam..',bold'
lexers.STYLE_EOF = 'fore:'..muted
